import Header from "./_components/Header";
import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";
import { ReservationProvider } from "./_components/ReservationContex";
import "./_styles/globals.css";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: {
    template: "%s/The Wild Oasis",
    default: "The Wild Oasis",
  },
  description: "Generated by Next.js",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} mx-auto antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col`}
      >
        <Header />
        <hr className="border-primary-100 mx-auto z-30 w-2/4" />
        <div
          className="flex-1 px-8 py-12
        "
        >
          <main className="max-w-7xl mx-auto ">
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
